# Generated by Django 4.2.13 on 2024-05-28 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(upload_to='fotos/%Y/%m/%d/')),
                ('data', models.DateTimeField(default=datetime.datetime(2024, 5, 28, 7, 57, 17, 473317))),
            ],
        ),
    ]
