# Generated by Django 4.2.13 on 2024-05-28 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheOneFitnessCenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 10, 4, 19, 335494)),
        ),
    ]
