# Generated by Django 4.2.13 on 2024-05-28 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheOneFitnessCenter', '0002_alter_assinatura_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 11, 49, 51, 114088)),
        ),
    ]
